# -*- coding: utf-8 -*-

"""
Created: Thu Jun 08 11:04:49 2017
@author: duxin
@email : duxin_be@outlook.com
Generated by PyDCollector
"""

from sys import path
path.append("../parse")
import pd_function
import mysqlconn
import githubapi

conn=mysqlconn.mysqlOpen(user="root",passwd="Csstsari107",host="rm-bp10rf4zreaw5he66o.mysql.rds.aliyuncs.com",port=3306,dbname="testPyDCollector")
connGA=mysqlconn.mysqlOpen(user="root",passwd="Csstsari107",host="rm-bp10rf4zreaw5he66o.mysql.rds.aliyuncs.com",port=3306,dbname="grabgithub")
mysqlconn.tryCreateTable(tablename="repos",columns="id int auto_increment primary key,reponame varchar(200)",conn=conn)
g,account=githubapi.createG(autofetch=True,conn=connGA)
rps=githubapi.getRepos(since=0,target=g)
raw_data=pd_function.pythonListTraverse(startid=0,target=rps,endid=100)
result=pd_function.filterReponame(startid=7,target=raw_data,endid=22)
mysqlconn.mysqlSave(tablename="repos",data=result,columns=["reponame"],conn=conn)
githubapi.releaseAccount(account=account,conn=connGA)
mysqlconn.mysqlClose(conn=conn)
mysqlconn.mysqlClose(conn=connGA)
